config/routes.rb
Rails.application.routes.draw do


  root to: 'projects#index'

  resources :users
  resources :projects
  resources :time_entries

  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/time_entry.rb
# == Schema Information
#
# Table name: time_entries
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  project_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  time       :decimal(, )
#  amount     :decimal(, )
#  end_time   :datetime
#  start_time :datetime
#

class TimeEntry < ApplicationRecord


  belongs_to :user, optional: true
  belongs_to :project, optional: true

  before_create :calculate_amount!
  before_create :calculate_time!
  # after_save :update_project_balance!

  # def entry_date_formatted
  #   self.entry_date.strftime '%d.%m.%Y' unless self.entry_date.nil?
  # end
  #
  # def entry_date_formatted=(value)
  #   return if value.nil? or value.blank?
  #   self.entry_date = DateTime.strptime(value, '%d.%m.%Y').to_date
  # end

  def self.per_hour
    50
  end

  def calculate_time!
    self.time = (self.end_time.to_i - self.start_time.to_i) / 3600
  end

  def calculate_amount!
    self.amount = TimeEntry.per_hour * self.calculate_time!
  end

  # def update_project_balance!
  #   self.project.update_balance!
  # end

end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :get_time_entry,  only: [:show, :edit, :update]

  before_action :check_if_logged_in

  before_action :check_if_admin, only: [:index]


  def get_time_entry
    @time_entry = TimeEntry.find params["id"]
  end

  def index
    # @time_entries = TimeEntry.all

    # get all time entries, grouped by project:
    # this returns a hash with THE WHOLE PROJECT OBJECT as the KEY
    # and an ARRAY OF TIME ENTRY OBJECTS (for that project) as the value
    # (use '.group_by(&:project_id)' to use use the ID as a key )
    # @entries = TimeEntry.where(user: @current_user).group_by(&:project)

    # check_if_admin
    if @current_user.is_admin
      @time_entries = TimeEntry.all
    else
      @time_entries = @current_user.time_entries
    end

  end

  def show
  end

  def new
    @time_entry = TimeEntry.new
    @user = @current_user
  end

  def create

    te = @current_user.time_entries.new(time_entry_params)

    s = params[:time_entry][:start_time].to_time
    e = params[:time_entry][:end_time].to_time

    te.start_time = s
    te.end_time = e

    if te.save
      redirect_to new_time_entry_path
    else
      render :new
    end

  end

  def edit

  end

  def update

    te = TimeEntry.find params[:id]
    te.start_time = params[:time_entry][:start_time].to_time
    te.end_time = params[:time_entry][:end_time].to_time

    if te.update(time_entry_params)
      redirect_to new_time_entry_path
    else
      render :new
    end

  end

  def destroy
    TimeEntry.find( params["id"]).destroy
    redirect_to new_time_entry_path
  end

  private
  def time_entry_params
    params.require(:time_entry).permit(:user_id, :project_id, :start_time, :end_time, :time, :amount)
  end
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/time_entries/_form.html.erb
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h3>
        Submit time form</h3>

      <%= form_for @time_entry do |f| %>
      <%= f.label :project %>
      <%= f.collection_select(:project_id, Project.all, :id, :name) %>
      <br>
      <%= f.label :start_time %>
      <%# Time.use_zone("Australia/Sydney") do %>
      <!-- <%#= f.datetime_select :start_time %> -->
      <%= f.text_field :start_time, class: 'datepicker' %>


      <%#= f.datetime_select :start_time, :value => Time.current.strftime('%d/%m/%Y') %>

      <!-- <%#= f.time_select :start_time, :ignore_date => true%> -->
      <%#= f.time_select :start_time %>
      <br>
      <%= f.label :end_time %>
      <!-- <%#= f.datetime_select :end_time %> -->
      <%= f.text_field :end_time, class: 'datepicker' %>
      <%#= f.date_select :end_time, :value => Time.zone.now %>
      <!-- <%#= f.time_select :end_time, :ignore_date => true %> -->
      <%#= f.time_select :end_time %>
      <br>
      <%# end %>
      <%= f.submit %>
      <% end %>

      <h3>Time Entries</h3>

      <% if @current_user.time_entries.any? %>
        <%= render partial: 'time_entry', collection: @current_user.time_entries.order('updated_at DESC') %>
      <% end %>


    </div>
  </div>

app/views/time_entries/_time_entry.html.erb
<div class="row">
    <div class="col-md-1"><div class="mini-box"><%= time_entry.user.name %></div></div>
    <div class="col-md-2"><div class="mini-box"><%= time_entry.project.name %></div></div>
    <div class="col-md-2"><div class="mini-box"><%= time_entry.start_time %></div></div>
    <div class="col-md-2"><div class="mini-box"><%= time_entry.end_time %></div></div>
    <div class="col-md-1"><div class="mini-box"><%= time_entry.time %></div></div>
    <div class="col-md-1"><div class="mini-box"><%= time_entry.amount %></div></div>
    <div class="col-md-1"><div class="mini-box"><%= link_to 'Edit', edit_time_entry_path(time_entry.id) %></div></div>
    <div class="col-md-1"><div class="mini-box"><%= link_to 'Delete', time_entry_path(time_entry.id), method: :delete, data: {confirm: 'Are you sure?'} %></div></div>
</div>

app/views/time_entries/edit.html.erb
<h2>Edit Time Entry</h2>

<%= render partial: 'form' %>

app/views/time_entries/index.html.erb
<div class="container">
  <!-- <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center"> -->
      <h2>Time Entries Index</h2>
      <%= render partial: 'time_entry', collection: @time_entries %>
      <!-- <ul>
        <%# @entries.each do |project, entry| %>
        <li>
          <strong><%#= project.name %></strong>

          <ul>
            <%# entry.each do |e| %>
            <li>
              <%#= e.user.name %>
              <%#= e.start_time.strftime "%m:%M %p %a %b %Y"  %>
              to
              <%#= e.end_time.strftime "%m:%M %p %a %b %Y" %></li>
            <%# end %>
          </ul>

          <%#= link_to time_entry.user.name, time_entry_path(time_entry.id) %>
        </li>
        <%# end %>
      </ul> -->
    <!-- </div>
  </div> -->
</div>

app/views/time_entries/new.html.erb
<h2>Create New Time Entry</h2>

<%= render partial: 'form' %>

app/views/time_entries/show.html.erb
<h2>Time Entry Details</h2>

<%= render partial: 'form' %>