config/routes.rb
Rails.application.routes.draw do


  root to: 'projects#index'

  resources :users
  resources :projects
  resources :time_entries

  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <!-- Latest compiled and minified CSS -->

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= cloudinary_js_config %>

    <link href="https://fonts.googleapis.com/css?family=Nunito|Oxygen|Source+Sans+Pro" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-default navbar-dark bg-inverse">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <%# left side menu of navigation bar %>
          <ul class="nav navbar-nav">
            <%# show sign up menu %>
            <li><%= link_to 'SIGN UP', new_user_path %>
            </li>

            <%# show login menu if user not already logged in %>
            <% unless @current_user.present? %>
            <li class="active">
              <%= link_to 'LOG IN', login_path, { :class=>"active" } %>
              <span class="sr-only">(current)</span>
            </li>

          <% else %>
            <%# User IS logged in %>
            <li><%= link_to 'LOG OUT', login_path, method: :delete %></li>
            <li><%= link_to "Welcome #{@current_user.name}", user_path( @current_user ) ,class:"welcome"%></li>
          </ul>

          <%# right side menu of navigation bar %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'LOG TIME', new_time_entry_path %></li>
            <!-- <li><%#= link_to 'TIME ENTRIES', time_entries_path %></li> -->

            <li><%= link_to 'PROJECTS', projects_path %></li>
            <li><%= link_to 'USERS', users_path %></li>

            <% end %>

          </ul>
        </div>
        <!-- /.navbar-collapse -->

      </nav>
    </div>
    <%# end container %>

    <%= yield %>


  </body>
</html>